npm install @angular/core --save
npm install @angular/common --save
npm install @angular/compiler --save
npm install @angular/forms --save
npm install @angular/http --save
npm install @angular/platform-browser --save
npm install @angular/platform-browser-dynamic --save
npm install @angular/router --save
npm install core-js --save
npm install rxjs --save
npm install zone.js --save
npm install babel-core --save-dev
npm install babel-loader --save-dev
npm install babel-preset-angular2 --save-dev
npm install babel-preset-latest --save-dev
npm install source-map-loader --save-dev
npm install webpack --save-dev
npm install copy-webpack-plugin --save-dev
